### ISSUE TITLE
actions: remove `done` callback from action-handler in favor of promise

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar_patterns#34]
Currently, the action handler can be completed either through a done-callback or by resolving/rejecting a promise.

To keep things simple, resolving/rejecting the promise should be the only way of completing an action. If nothing is returned, the action should probably be completed immediately with success.

**Comment by alex3683** [comment]
Additionally the explicit configuration of an asynchronous action handler can be removed.
Following rules will be applied to the (possible) return value of the handler.

### the handler throws an error:
* the `didTakeAction` is sent with outcome `ERROR`
* the error is re-thrown

### the handler returns a simple value or a promise, that is later resolved with a value
* if the value is a plain object, it is used as basis for the event object and
* if the object has a property `outcome` with value `ERROR`, the `didTakeAction` is sent with outcome `ERROR`
* otherwise, or if the value is no plain object, the `didTakeAction` is sent with outcome `SUCCESS`

### the handler returns a promise, that is later rejected with a value
* if the value is a plain object, it is used as basis for the event object and
* if the object has a property `outcome` with value `SUCCESS`, the `didTakeAction` is sent with outcome `SUCCESS`
* otherwise, or if the value is no plain object, the `didTakeAction` is sent with outcome `ERROR`

**Comment by alex3683** [comment]
- the handler throws an error
 - the `didTakeAction` is sent with outcome `ERROR`
 - the error is re-thrown

**Comment by alex3683** [comment]
## Breaking Change
`done` callbacks in action-handlers are no longer supported. Instead an asynchronous action-handler has to signal completeness via Promise. As a consequence it is no longer necessary to pass an option `{async: true }` when registering the handler, as a promise as return value always yields an asynchronous handler.
Example:
Before:
```
patterns.actions.handlerFor( $scope )
   .registerActions( [ 'closeAction', 'shutdownAction' ], function( event, meta, done ) {
      doSomethingAsynchronous().then( done, done );
   }, { async: true } );
```
Now:
```
patterns.actions.handlerFor( $scope )
   .registerActions( [ 'closeAction', 'shutdownAction' ], function( event, meta ) {
      return doSomethingAsynchronous();
   } );
```
